title: v32231's tiny blog
description: V32231의 개인 블로그
lang: ko
timezone: Asia/Seoul
url: https://v32231.github.io
remote_theme: v32231/v32231.github.io_theme
plugins: 
- jekyll-remote-theme
navigation_header:
- title: v32231's tiny blog
  url: /
- title: Development
  url: /categories/d/
- title: CTF/Wargame
  url: /categories/cw/
- title: BugBounty
  url: /categories/bb/
- title: Blog/TechDocs
  url: /categories/bd/
- title: Contests/Certifications
  url: /categories/cc/
- title: Papers/Conferences
  url: /categories/pc/
